db:
  uri: "postgresql://postgres:postgres@localhost:5432/"
  pool_size: 20
  max_overflow: 10

broker:
  uri: "redis://localhost:6379/0"

server:
  cors:
    - "*"

logger:
  path: "logs/app.json"
  rotation: "10 MB"
  level: "INFO"