db:
  uri: "postgresql+asyncpg://postgres:postgres@localhost:5432"

cache:
  uri: "memory://"
  max_content_size: 0
  ttls:
    "/v1/notifications/": 1000
    "/v1/notifications/{notification_id}": 60
    "/v1/notifications/{notification_id}/status": 300

broker:
  uri: "sqla+sqlite:///celerydb.sqlite"

server:
  cors: ["*"]

logger:
  path: "logs/app.json"
  rotation: "10 MB"
  level: "DEBUG"