db:
  uri: "sqlite+aiosqlite:///db.sqlite"

cache:
  uri: "memory://"
  max_content_size: 0
  ttls:
    "/v1/notifications/": 30
    "/v1/notifications/{notification_id}": 60
    "/v1/notifications/{notification_id}/status": 300

broker:
  uri: "sqla+sqlite:///broker.sqlite"

server:
  cors: ["*"]

logger:
  level: "DEBUG"